version: '3.9'
services:
  app:
    image: sonakul/group4-deployment
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9001:80
    environment:
      - HOST=0.0.0.0
      - PORT=80